### ISSUE TITLE
Pagination in ag-grid-ng2

### ISSUE THREAD

**Issue by pantonis** [ceolter/ag-grid-ng2-example#8]
Can you please give an example of how pagination is done using ag-grid-ng2?

Thanks

**Comment by floriecai** [comment]
+ 1 (specifically server side pagination)

**Comment by ceolter** [comment]
there is not difference between ng2 and normal.

one person did point out in react, setting the datasource at the start didn't work (which i'll be fixing in the next release). can you try setting the datasource after the grid is created?

otherwise, provide a question what's wrong - maybe i can answer.

we don't have the resources to provide examples for all the different frameworks.

**Comment by olegkon** [comment]
Hi,
I understand how ag-grid-ng2 works with hardcoded data.But what if I have a JSON feed of data, lets say from external Weather service,so as an input I have a WeatherRow array, whereWeatherRow is a VA with  String(s) temperature, wind, humidity, etc.
How to populate that  ag-grid-ng2, how would that code look like?Any similar samples?
Thank you in advance,  Oleg. 

    On Thursday, June 30, 2016 2:51 AM, Niall Crosby <notifications@github.com> wrote:
 

 Closed #8.—

**Comment by sskmail14** [comment]
This might help you...
It worked for me!!!
[http://stackoverflow.com/questions/36934207/angular2-ag-grid-datasource](http://stackoverflow.com/questions/36934207/angular2-ag-grid-datasource)
